### ISSUE TITLE
IS `bit_string` the wrong token for nested bits?

### ISSUE THREAD

**Issue by dusty-phillips** [lpil/glance#22]
I'm looking here:

https://github.com/lpil/glance/blob/main/src/glance.gleam#L1110

This doesn't seem to be valid gleam. I *think* it's supposed to be `bits`?

This parses successfully with `glance`, but it is an error when parsed with the gleam compiler.

```gleam
  let x = <<<<32:16>>:bit_string, <<32>>:bit_string>>
```

Conversely, this parses correctly with the gleam compiler, but is a UnexpectedToken error in glance:

```gleam
  let x = <<<<32:16>>:bits, <<32>>:bits>>
```

**Comment by dusty-phillips** [comment]
I suspect "binary" is supposed to be "bytes" as well.

**Comment by lpil** [comment]
Glance is permissive and supports more syntaxes than the compiler parser. These specifically enable the parsing of some older versions of Gleam.

**Comment by dusty-phillips** [comment]
@lpil that makes sense, but I think it's not parsing the *current* compiler syntax. 

I'm obviously not clear on the history, but  if glance is supposed to be more permissive than the compiler, I think it should accept `:bits`, since the compiler parser does so?

**Comment by lpil** [comment]
It should! Yes
